export const GET_ALL_USERS = "GET_ALL_USERS"

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST"

export const DELETE_USER = "DELETE_USER"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"

export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"
